name: Publish to GitHub wiki
description: 📖 GitHub Action to sync a folder to the GitHub wiki
author: Jacob Hummer
branding:
  icon: book-open
  color: blue
inputs:
  path:
    description:
      Path to the wiki folder with Markdown files in it. Usually this is
      something like "wiki" or "docs". Defaults to "wiki".
    required: true
    default: wiki
outputs:
  page_url:
    description: Deployed wiki URL. Links to GitHub wiki Home page.
    value: ${{ steps.gh-action.outputs.page_url }}
runs:
  using: composite
  steps:
    - id: gh-action
      run: |
        "$GITHUB_ACTION_PATH/src/gh-action.sh"
      shell: bash
      # https://github.com/actions/runner/issues/665
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_PATH: ${{ inputs.path }}
