name: Test publish to own wiki
on:
  push:
    paths: [src/**, action.yml, .github/workflows/test-publish-to-own-wiki.yml]
concurrency: test-publish-to-own-wiki-${{ github.ref }}
jobs:
  test-publish-to-own-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - run: |
          mkdir wiki
          echo "$GITHUB_WORKFLOW" > wiki/Test.md
          git add wiki
          git commit --amend --no-edit
      - uses: ./
